export const perSlug = [
    {
        VIEW_DASHBOARD: "view_dashboard",
        VIEW_ROLE_LIST: "view_role_list",
        ADD_NEW_ROLE: "add_new_role",
        EDIT_ROLE: "edit_role",
        DELETE_ROLE: "delete_role",
        SET_ROLE_PERMISSION: "set_role_permission",
        VIEW_MENU_LIST: "view_menu_list",
        ADD_NEW_MENU: "add_new_menu",
        EDIT_MENU: "edit_menu",
        DELETE_MENU: "delete_menu",
        VIEW_PERMISSION_LIST: "view_permission_list",
        ADD_NEW_PERMISSION: "add_new_permission",
        EDIT_PERMISSION: "edit_permission",
        VIEW_USER_LIST: "view_user_list",
        ADD_NEW_USER: "add_new_user",
        EDIT_USER: "edit_user",
        EDIT_USER_STATUS_ACTIVE_INACTIVE: "edit_user_status_active_inactive",
        SET_USER_ROLE: "set_user_role",
        CHANGE_PASSWORD_USER: "change_password_user",
        VIEW_SCHEDULE: "view_schedule",
        VIEW_NUMBER_OF_LOCATION: "view_number_of_location",
        VIEW_NUMBER_OF_MISSIONARY: "view_number_of_missionary",
        VIEW_EVENT_CATEGORIES_TYPE: "view_event_categories_type",
        ADD_EVENT_CATEGORIES_TYPE: "add_event_categories_type",
        EDIT_EVENT_CATEGORIES_TYPE: "edit_event_categories_type",
        DELETE_EVENT_CATEGORIES_TYPE: "delete_event_categories_type",
        VIEW_EVENT_REPORT: "view_event_report",
        VIEW_STATISTIC_ACTIVITY: "view_statistic_activity",
        VIEW_SLIDER: "view_slider",
        ADD_SLIDER: "add_slider",
        EDIT_SLIDER: "edit_slider",
        DELETE_SLIDER: "delete_slider",
        VIEW_TEXT_NOTIFICATION: "view_text_notification",
        ADD_TEXT_NOTIFICATION: "add_text_notification",
        EDIT_TEXT_NOTIFICATION: "edit_text_notification",
        DELETE_TEXT_NOTIFICATION: "delete_text_notification",
    },
]